name: Build and Deploy Flutter Web to GitHub Pages

# 何時觸發 Workflow
on:
  push:
    branches:
      - main # 或者 master，取決於您的主要分支名稱
  # 允許手動從 Actions 標籤頁運行此 Workflow
  workflow_dispatch:

# Workflow 運行的作業 (jobs)
jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 運行器

    steps:
      # 步驟 1: Checkout 您的倉庫代碼
      - name: Checkout repository
        uses: actions/checkout@v4 # 使用官方的 checkout action

      # 步驟 2: 設定 Flutter 環境
      # 使用 subosito/flutter-action 這個流行的社群 Action 來設定 Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # 或者 'beta', 'dev', 'master'，建議使用 stable
          # flutter-version: '3.x.x' # 可選：指定特定的 Flutter 版本

      # 步驟 3: (可選) 獲取 Flutter 依賴包
      - name: Get Flutter dependencies
        run: flutter pub get

      # 步驟 4: (可選) 運行測試
      # - name: Run Flutter tests
      #   run: flutter test

      # 步驟 5: 建置 Flutter Web 應用
      # 預設情況下，Flutter Web 應用會建置到專案根目錄下的 build/web 資料夾
      # --base-href 是重要的，如果您的 GitHub Pages 網址是 <username>.github.io/<repository-name>/
      # 則 base-href 應該是 /<repository-name>/
      # 如果您的 GitHub Pages 網址是 <username>.github.io (用戶/組織站點)，則不需要 --base-href 或者設為 /
      - name: Build Flutter Web
        run: flutter build web --release --base-href /${{ github.event.repository.name }}/
        # 如果是部署到用戶/組織根站點 (例如 <username>.github.io)，則使用:
        # run: flutter build web --release --base-href /
        # 或者直接:
        # run: flutter build web --release

      # 步驟 6: 部署到 GitHub Pages
      # 使用 peaceiris/actions-gh-pages 這個流行的社群 Action 來部署
      # 它會將 build/web 資料夾的內容推送到 gh-pages 分支 (或其他指定分支)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # GitHub 自動提供的 token，用於授權推送到倉庫
          publish_dir: ./build/web # 指定要部署的資料夾
          publish_branch: gh-pages # 指定要推送到哪個分支 (GitHub Pages 會從此分支提供服務)
          # user_name: 'github-actions[bot]' # 可選：自定義 commit 的用戶名
          # user_email: 'github-actions[bot]@users.noreply.github.com' # 可選：自定義 commit 的用戶郵箱
          # commit_message: 'Deploy Flutter Web to GitHub Pages' # 可選：自定義 commit 訊息
          # cname: your-custom-domain.com # 可選：如果您使用自訂域名
          # force_orphan: true # 可選：創建一個乾淨的、沒有歷史記錄的分支 (對於 gh-pages 常用)
          # keep_files: false # 可選：在部署前是否保留目標分支上的現有文件，設為 false 會清除舊文件